user-story/1442-as-a-user,-i-want-to-track-detections-over-multiple-videos
OpenTrafficCam/OTVision pull request #203
Opened 2023-02-07 08:01 UTC by briemla

OP#1442

2023-02-17 12:10 UTC, briemla commented on OTVision/dataformat.py
> +METADATA: str = "metadata"
This file will be extended in OP#1541 New output format. All files will be checked and strings will be replaced in OP#1541

2023-02-17 12:13 UTC, briemla commented on OTVision/helpers/files.py
> +def _denormalize_transformation(
Denormalization and normalization have been separated again. The update of metadata is different in both methods. Therefore, the separation was necessary.

Metadata will now be read by frame, as frames belong to different video files.

2023-02-17 12:13 UTC, briemla commented on OTVision/helpers/files.py
> +def _normalize_transformation(
See comment at `_denormalize_transformation`

2023-02-20 16:32 UTC, randy-seng requested changes
Looks good! I just have a few comments to be resolved~

2023-02-20 16:32 UTC, randy-seng commented on OTVision/track/preprocess.py
> +    def __init__(self, no_frames_for: timedelta = timedelta(minutes=1)) -> None:
Can we rename `no_frames_for` to `time_without_frames`?

2023-02-21 13:42 UTC, briemla commented on OTVision/detect/detect.py
> +    "_(?P<start_date>\\d{4}-\\d{2}-\\d{2}_\\d{2}-\\d{2}-\\d{2})\\..*"
Thanks, nice feature.

2023-02-21 14:45 UTC, randy-seng approved these changes

2023-02-23 14:46 UTC, martinbaerwolff approved these changes
Looks good, I ran detection and tracking using your branch and the IDs are consecutive for consecutive .ottrk files from consecutive videos :)

However, I got a log `metadata updated from historic format to new format` during tracking, but I assume this can be fixed with OP#1541

2023-02-24 07:16 UTC, merged