new_detections only as comments, determine the label of the tracks wi…
OpenTrafficCam/OTVision pull request #58
Opened 2021-02-05 18:18 UTC by arminkollascheck

…th a dataframe (.mode) instead of .count function (way faster), dont copy informations of the last assigned detection of the track during gaps

Only returns the "tracks_finished" instead of "new_detections, tracks_finished". Could be a problem for functions that use the track_iou() function, even if they dont use the new_detections.

2021-02-05 18:35 UTC, martinbaerwolff commented
@frunika do u want to discard the outcommented sections?

2021-02-05 18:38 UTC, martinbaerwolff commented
@arminkollascheck thanks for tremendously boosting the pipeline ;)

2021-02-05 18:49 UTC, arminkollascheck reviewed
If you want to reverse the new_detections change.

2021-02-05 18:49 UTC, arminkollascheck commented on OTVision/track/iou_tracker_qp.py
>      # return new_detections, tracks_finished
also if you want the change it to the old with new_detections

2021-02-05 18:49 UTC, arminkollascheck commented on OTVision/track/iou_tracker_qp.py
>      # return new_detections, tracks_finished
and line 44, 50 and the 74 following

2021-02-14 22:44 UTC, frunika requested changes
just some minor changes due to docstring usage :)

Thanks for implementation @arminkollascheck

2021-02-14 22:44 UTC, frunika commented on OTVision/track/iou_tracker_qp.py
> +                    """best_match["vehID"] = track["vehID"]
Don't use docstrings as comment. Use line comment (#)

2021-02-14 22:44 UTC, frunika commented on OTVision/track/iou_tracker_qp.py
> +        track["max_label"] = pd.Series(track["labels"]).mode().iat[0]
nice one ;)

2021-03-10 20:56 UTC, arminkollascheck commented
Ok

2021-03-10 21:29 UTC, merged